language: node_js
node_js:
- '10'

before_install:
- openssl aes-256-cbc -K $encrypted_da8469ada713_key -iv $encrypted_da8469ada713_iv
  -in deploy_rsa.enc -out deploy_rsa -d

addons:
  ssh_known_hosts: vapor.fm

before_deploy:
- openssl aes-256-cbc -K $encrypted_da8469ada713_key -iv $encrypted_da8469ada713_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

script:
- npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -a --delete-after --quiet $TRAVIS_BUILD_DIR/dist/ $ssh_user@vapor.fm:/var/www/html
  on:
    branch: master
